# Cannot use the checkout@v3 or v4 action on ubuntu18.04 because of nodejs
# version.
#- name: checkout
#  uses: actions/checkout@v3
#  with: {submodules: recursive}
# Needed for running in the docker image.
# See https://github.com/actions/checkout/issues/1169
#- run: git config --system --add safe.directory '*'
#... so we checkout manually:
- name: checkout
  run: |
    set -x
    echo GITHUB_REF=$GITHUB_REF
    echo GITHUB_HEAD_REF=$GITHUB_HEAD_REF
    branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}  # https://stackoverflow.com/questions/58033366
    echo branch=$branch
    git init -q .
    git config --system --add safe.directory '*'  # needed for running in the docker image. see https://github.com/actions/checkout/issues/1169
    git remote add origin $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
    git fetch origin $branch
    git reset --hard FETCH_HEAD
    git submodule update --init --recursive
