!yamlscript/v0:

:: use(common)
:: workflow-setup()
common-steps =: load('share/steps.yaml')

env:
  PROJ_PFX_TARGET: ryml-
  PROJ_PFX_CMAKE: RYML_
  CMAKE_FLAGS: -DRYML_TEST_SUITE=ON
  NUM_JOBS_BUILD: # 4


jobs:

  #----------------------------------------------------------------------------
  clang_tidy:
    name: clang_tidy/c++${{matrix.std}}/${{matrix.bt}}
    continue-on-error: true
    if: always()  # https://stackoverflow.com/questions/62045967/github-actions-is-there-a-way-to-continue-on-error-while-still-getting-correct
    runs-on: ubuntu-latest
    container: ghcr.io/biojppm/c4core/ubuntu22.04:latest  # use the docker image
    strategy:
      fail-fast: false
      matrix:
        item =: \({:std 11, :cxx 'clang++-17', :bt %2,
                   :lint 'clang-tidy', :bitlinks %1})
        include:
        # clang tidy takes a long time,
        # so don't do multiple bits/linktypes
        - ! item('shared64' 'Debug')
        - ! item('shared32' 'Debug')
        - ! item('static64' 'Debug')
        - ! item('static32' 'Debug')
        - ! item('shared64' 'ReleaseWithDebInfo')
        - ! item('shared32' 'ReleaseWithDebInfo')
        - ! item('static64' 'ReleaseWithDebInfo')
        - ! item('static32' 'ReleaseWithDebInfo')

    env: {STD: "${{matrix.std}}", CXX_: "${{matrix.cxx}}", BT: "${{matrix.bt}}", BITLINKS: "${{matrix.bitlinks}}", VG: "${{matrix.vg}}", SAN: "${{matrix.san}}", LINT: "${{matrix.lint}}", OS: "${{matrix.os}}"}
    steps:
    - {name: checkout, uses: actions/checkout@v4, with: {submodules: recursive}}
    - run: git config --system --add safe.directory '*'  # needed for running in the docker image. see https://github.com/actions/checkout/issues/1169
    - :: common-steps
