!yamlscript/v0:

:: use(common)
:: workflow-setup()
common-steps =: load('share/steps.yaml')

env:
  PROJ_PFX_TARGET: ryml-
  PROJ_PFX_CMAKE: RYML_
  CMAKE_FLAGS: -DRYML_TEST_SUITE=ON
  NUM_JOBS_BUILD: # 4

jobs:
  clang_tidy:
    name: clang_tidy/c++${{matrix.std}}/${{matrix.bt}}
    continue-on-error: true
    if: always()  # https://stackoverflow.com/a/62112985/721703
    runs-on: ubuntu-latest
    container: ghcr.io/biojppm/c4core/ubuntu22.04:latest

    strategy:
      fail-fast: false
      matrix:
        item =:
          \({:std 11, :cxx 'clang++-17', :bt %2,
             :lint 'clang-tidy', :bitlinks %1})
        include:
        # clang tidy takes a long time,
        # so don't do multiple bits/linktypes
        - ! item('shared64' 'Debug')
        - ! item('shared32' 'Debug')
        - ! item('static64' 'Debug')
        - ! item('static32' 'Debug')
        - ! item('shared64' 'ReleaseWithDebInfo')
        - ! item('shared32' 'ReleaseWithDebInfo')
        - ! item('static64' 'ReleaseWithDebInfo')
        - ! item('static32' 'ReleaseWithDebInfo')

    env:: load('share/env.yaml')

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with: {submodules: recursive}
    # needed for running in the docker image.
    # see https://github.com/actions/checkout/issues/1169
    - run: git config --system --add safe.directory '*'
    - :: common-steps
