!yamlscript/v0:

:: use(common)
:: workflow-setup()
common-steps =: load('share/steps.yaml')

env:
  PROJ_PFX_TARGET: ryml-
  PROJ_PFX_CMAKE: RYML_
  CMAKE_FLAGS: -DRYML_TEST_SUITE=ON
  NUM_JOBS_BUILD: # 4


jobs:

  #----------------------------------------------------------------------------
  macosx:
    if: |
      (!contains(github.event.head_commit.message, 'skip all')) ||
      (!contains(github.event.head_commit.message, 'skip macosx')) ||
      contains(github.event.head_commit.message, 'only macosx')
    continue-on-error: true
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
        - {std: 11, cxx: xcode, xcver: 15, bt: Debug  , os: macos-13, bitlinks: shared64 static64}
        - {std: 11, cxx: xcode, xcver: 15, bt: Release, os: macos-13, bitlinks: shared64 static64}
        - {std: 17, cxx: xcode, xcver: 15, bt: Debug  , os: macos-13, bitlinks: shared64 static64}
        - {std: 17, cxx: xcode, xcver: 15, bt: Release, os: macos-13, bitlinks: shared64 static64}
        #
        - {std: 11, cxx: xcode, xcver: 14, bt: Debug  , os: macos-13, bitlinks: shared64 static64}
        - {std: 11, cxx: xcode, xcver: 14, bt: Release, os: macos-13, bitlinks: shared64 static64}
        - {std: 17, cxx: xcode, xcver: 14, bt: Debug  , os: macos-13, bitlinks: shared64 static64}
        - {std: 17, cxx: xcode, xcver: 14, bt: Release, os: macos-13, bitlinks: shared64 static64}
    env: {STD: "${{matrix.std}}", CXX_: "${{matrix.cxx}}", BT: "${{matrix.bt}}", BITLINKS: "${{matrix.bitlinks}}", VG: "${{matrix.vg}}", SAN: "${{matrix.san}}", LINT: "${{matrix.lint}}", OS: "${{matrix.os}}"}
    steps:
    - {name: checkout, uses: actions/checkout@v4, with: {submodules: recursive}}
    - {name: xcode, uses: maxim-lobanov/setup-xcode@v1, with: {xcode-version: "${{matrix.xcver}}" }}
    - {name: install requirements, run: source .github/reqs.sh && c4_install_test_requirements $OS}
    - :: common-steps.drop(1)
